import { Shard } from './shard';

export const SHARDTYPES: string[] = [
    "Mover",
    "Shaker",
    "Brute",
    "Breaker",
    "Master",
    "Tinker",
    "Blaster",
    "Thinker",
    "Striker",
    "Changer",
    "Trump",
    "Stranger"
]

export const SHARDLIST: Shard[] = [
    { id: 1, pointCost: 1, name: "Jump", description: "DESC", type: 1},
    { id: 2, pointCost: 2, name: "No Clip", description: "DESC", type: 1},
    { id: 3, pointCost: 2, name: "Remote Transfer", description: "DESC", type: 1},
    { id: 4, pointCost: 3, name: "Flight", description: "DESC", type: 1},
    { id: 5, pointCost: 5, name: "Beacon", description: "DESC", type: 1},
    { id: 6, pointCost: 5, name: "Blitz", description: "DESC", type: 1},
    { id: 7, pointCost: 7, name: "Blink", description: "DESC", type: 1},
    { id: 8, pointCost: 7, name: "Summoning", description: "DESC", type: 1},
    { id: 9, pointCost: 10, name: "Offscreen Travel", description: "DESC", type: 1},
    { id: 10, pointCost: 10, name: "Hyper Speed", description: "DESC", type: 1},
    { id: 11, pointCost: 25, name: "Planewalk", description: "DESC", type: 1},
    { id: 12, pointCost: 1, name: "Pocket Room", description: "DESC", type: 2},
    { id: 13, pointCost: 2, name: "Barrier", description: "DESC", type: 2},
    { id: 14, pointCost: 2, name: "Sound Control", description: "DESC", type: 2},
    { id: 15, pointCost: 3, name: "Omnicombustion", description: "DESC", type: 2},
    { id: 16, pointCost: 5, name: "Stark Winter", description: "DESC", type: 2},
    { id: 17, pointCost: 5, name: "Insomnia", description: "DESC", type: 2},
    { id: 18, pointCost: 7, name: "Temporal Bubble", description: "DESC", type: 2},
    { id: 19, pointCost: 7, name: "Gravity Control", description: "DESC", type: 2},
    { id: 20, pointCost: 10, name: "Infinite Treasury", description: "DESC", type: 2},
    { id: 21, pointCost: 10, name: "Atmosphere Control", description: "DESC", type: 2},
    { id: 22, pointCost: 25, name: "Ultimate Luck", description: "DESC", type: 2},
    { id: 23, pointCost: 1, name: "Peak Condition", description: "DESC", type: 3},
    { id: 24, pointCost: 2, name: "Vampirism", description: "DESC", type: 3},
    { id: 25, pointCost: 2, name: "Mountain", description: "DESC", type: 3},
    { id: 26, pointCost: 3, name: "Do You Even Lift", description: "DESC", type: 3},
    { id: 27, pointCost: 5, name: "Damage Sharing", description: "DESC", type: 3},
    { id: 28, pointCost: 5, name: "Personal Forcefield", description: "DESC", type: 3},
    { id: 29, pointCost: 7, name: "Rocky", description: "DESC", type: 3},
    { id: 30, pointCost: 7, name: "Training Montage", description: "DESC", type: 3},
    { id: 31, pointCost: 10, name: "Invulnerability", description: "DESC", type: 3},
    { id: 32, pointCost: 10, name: "Regeneration", description: "DESC", type: 3},
    { id: 33, pointCost: 25, name: "Broken Limiter", description: "DESC", type: 3},
    { id: 34, pointCost: 1, name: "Immunity", description: "DESC", type: 4},
    { id: 35, pointCost: 2, name: "Elasticity", description: "DESC", type: 4},
    { id: 36, pointCost: 2, name: "Trance", description: "DESC", type: 4},
    { id: 37, pointCost: 3, name: "Shrinking", description: "DESC", type: 4},
    { id: 38, pointCost: 5, name: "Shroedinger", description: "DESC", type: 4},
    { id: 39, pointCost: 5, name: "Mirror, Mirror", description: "DESC", type: 4},
    { id: 40, pointCost: 7, name: "Temporal Leap", description: "DESC", type: 4},
    { id: 41, pointCost: 7, name: "Machine Spirit", description: "DESC", type: 4},
    { id: 42, pointCost: 10, name: "Komnenos", description: "DESC", type: 4},
    { id: 43, pointCost: 10, name: "Respawn", description: "DESC", type: 4},
    { id: 44, pointCost: 25, name: "Perpetuance", description: "DESC", type: 4},
    { id: 45, pointCost: 1, name: "Protocols", description: "DESC", type: 5},
    { id: 46, pointCost: 2, name: "Mirror Image", description: "DESC", type: 5},
    { id: 47, pointCost: 2, name: "Technopathy", description: "DESC", type: 5},
    { id: 48, pointCost: 3, name: "lawgiver", description: "DESC", type: 5},
    { id: 49, pointCost: 5, name: "Suzerain", description: "DESC", type: 5},
    { id: 50, pointCost: 5, name: "Animate Constructs", description: "DESC", type: 5},
    { id: 51, pointCost: 7, name: "Stand", description: "DESC", type: 5},
    { id: 52, pointCost: 7, name: "Destiny Weaver", description: "DESC", type: 5},
    { id: 53, pointCost: 10, name: "Replication", description: "DESC", type: 5},
    { id: 54, pointCost: 10, name: "Enthrallment", description: "DESC", type: 5},
    { id: 55, pointCost: 25, name: "Bringing An End", description: "DESC", type: 5},
    { id: 56, pointCost: 1, name: "Macgyver", description: "DESC", type: 6},
    { id: 57, pointCost: 2, name: "Repair", description: "DESC", type: 6},
    { id: 58, pointCost: 2, name: "Radar", description: "DESC", type: 6},
    { id: 59, pointCost: 3, name: "Small Arms", description: "DESC", type: 6},
    { id: 60, pointCost: 5, name: "Augmentation", description: "DESC", type: 6},
    { id: 61, pointCost: 5, name: "Armoured Warfare", description: "DESC", type: 6},
    { id: 62, pointCost: 7, name: "Fortification", description: "DESC", type: 6},
    { id: 63, pointCost: 7, name: "Robotics", description: "DESC", type: 6},
    { id: 64, pointCost: 10, name: "Genetics", description: "DESC", type: 6},
    { id: 65, pointCost: 10, name: "Nanomachines", description: "DESC", type: 6},
    { id: 66, pointCost: 25, name: "Wavelength", description: "DESC", type: 6},
    { id: 67, pointCost: 1, name: "Infinite Ammo", description: "DESC", type: 7},
    { id: 68, pointCost: 2, name: "Boomerang", description: "DESC", type: 7},
    { id: 69, pointCost: 2, name: "Get Over Here", description: "DESC", type: 7},
    { id: 70, pointCost: 3, name: "Bullet Hell", description: "DESC", type: 7},
    { id: 71, pointCost: 5, name: "Chain Lightning", description: "DESC", type: 7},
    { id: 72, pointCost: 5, name: "Homing System", description: "DESC", type: 7},
    { id: 73, pointCost: 7, name: "Voodoo", description: "DESC", type: 7},
    { id: 74, pointCost: 7, name: "Temporal Blast", description: "DESC", type: 7},
    { id: 75, pointCost: 10, name: "Sting", description: "DESC", type: 7},
    { id: 76, pointCost: 10, name: "Telekinesis", description: "DESC", type: 7},
    { id: 77, pointCost: 25, name: "Causality Reversal", description: "DESC", type: 7},
    { id: 78, pointCost: 1, name: "X-ray Vision", description: "DESC", type: 8},
    { id: 79, pointCost: 2, name: "Proficiency", description: "DESC", type: 8},
    { id: 80, pointCost: 2, name: "Presence", description: "DESC", type: 8},
    { id: 81, pointCost: 3, name: "True or False", description: "DESC", type: 8},
    { id: 82, pointCost: 5, name: "Perfect Mind", description: "DESC", type: 8},
    { id: 83, pointCost: 5, name: "Retrospective", description: "DESC", type: 8},
    { id: 84, pointCost: 7, name: "Glimpse", description: "DESC", type: 8},
    { id: 85, pointCost: 7, name: "Hindsight", description: "DESC", type: 8},
    { id: 86, pointCost: 10, name: "Fake Telepathy", description: "DESC", type: 8},
    { id: 87, pointCost: 10, name: "Save and Reload", description: "DESC", type: 8},
    { id: 88, pointCost: 25, name: "Path to Victory", description: "DESC", type: 8},
    { id: 89, pointCost: 1, name: "Shock and Awe", description: "DESC", type: 9},
    { id: 90, pointCost: 2, name: "Revenant", description: "DESC", type: 9},
    { id: 91, pointCost: 2, name: "Vector Push", description: "DESC", type: 9},
    { id: 92, pointCost: 3, name: "Quality Assurance", description: "DESC", type: 9},
    { id: 93, pointCost: 5, name: "Temporal Overwrite", description: "DESC", type: 9},
    { id: 94, pointCost: 5, name: "Paralysis", description: "DESC", type: 9},
    { id: 95, pointCost: 7, name: "Accelerated Decay", description: "DESC", type: 9},
    { id: 96, pointCost: 7, name: "Surgery", description: "DESC", type: 9},
    { id: 97, pointCost: 10, name: "Combo", description: "DESC", type: 9},
    { id: 98, pointCost: 10, name: "Body Swap", description: "DESC", type: 9},
    { id: 99, pointCost: 25, name: "Death Perception", description: "DESC", type: 9},
    { id: 100, pointCost: 1, name: "Cosmetic Shapeshift", description: "DESC", type: 10},
    { id: 101, pointCost: 2, name: "Razor Hand", description: "DESC", type: 10},
    { id: 102, pointCost: 2, name: "Stone Skin", description: "DESC", type: 10},
    { id: 103, pointCost: 3, name: "Elemental", description: "DESC", type: 10},
    { id: 104, pointCost: 5, name: "Animorph", description: "DESC", type: 10},
    { id: 105, pointCost: 5, name: "Survivalism", description: "DESC", type: 10},
    { id: 106, pointCost: 7, name: "Consumption", description: "DESC", type: 10},
    { id: 107, pointCost: 7, name: "Mist Shift", description: "DESC", type: 10},
    { id: 108, pointCost: 10, name: "Infection", description: "DESC", type: 10},
    { id: 109, pointCost: 10, name: "Living Forest", description: "DESC", type: 10},
    { id: 110, pointCost: 25, name: "Final Form", description: "DESC", type: 10},
    { id: 111, pointCost: 1, name: "Power Sight", description: "DESC", type: 11},
    { id: 112, pointCost: 2, name: "Exchange", description: "DESC", type: 11},
    { id: 113, pointCost: 2, name: "Copycat", description: "DESC", type: 11},
    { id: 114, pointCost: 3, name: "Power Hub", description: "DESC", type: 11},
    { id: 115, pointCost: 5, name: "Counter", description: "DESC", type: 11},
    { id: 116, pointCost: 5, name: "Power Fluctuation", description: "DESC", type: 11},
    { id: 117, pointCost: 7, name: "Unlimited Shard Works", description: "DESC", type: 11},
    { id: 118, pointCost: 7, name: "Adaptation", description: "DESC", type: 11},
    { id: 119, pointCost: 10, name: "Paramount", description: "DESC", type: 11},
    { id: 120, pointCost: 10, name: "Kingmaker", description: "DESC", type: 11},
    { id: 121, pointCost: 25, name: "Shardministartion", description: "DESC", type: 11},
    { id: 122, pointCost: 1, name: "Fake Death", description: "DESC", type: 12},
    { id: 123, pointCost: 2, name: "Recordless", description: "DESC", type: 12},
    { id: 124, pointCost: 2, name: "Who was Phone", description: "DESC", type: 12},
    { id: 125, pointCost: 3, name: "Fresh Identity", description: "DESC", type: 12},
    { id: 126, pointCost: 5, name: "Crowd Blending", description: "DESC", type: 12},
    { id: 127, pointCost: 5, name: "Terra Incognita", description: "DESC", type: 12},
    { id: 128, pointCost: 7, name: "Cloak", description: "DESC", type: 12},
    { id: 129, pointCost: 7, name: "Bluff", description: "DESC", type: 12},
    { id: 130, pointCost: 10, name: "Masquarade", description: "DESC", type: 12},
    { id: 131, pointCost: 10, name: "Oblivion", description: "DESC", type: 12},
    { id: 132, pointCost: 25, name: "Observer", description: "DESC", type: 12}
]